### ISSUE TITLE
Error while parsing GPX file from filepath

### ISSUE THREAD

**Issue by aeiou-st** [ticofab/android-gpx-parser#53]
` java.lang.IllegalArgumentException: Invalid format: ""
                            	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:947)
                            	at io.ticofab.androidgpxparser.parser.GPXParser.readTime(GPXParser.java:500)
                            	at io.ticofab.androidgpxparser.parser.GPXParser.readPoint(GPXParser.java:319)
                            	at io.ticofab.androidgpxparser.parser.GPXParser.readTrackPoint(GPXParser.java:461)
                            	at io.ticofab.androidgpxparser.parser.GPXParser.readSegment(GPXParser.java:233)
                            	at io.ticofab.androidgpxparser.parser.GPXParser.readTrack(GPXParser.java:149)
                            	at io.ticofab.androidgpxparser.parser.GPXParser.readGpx(GPXParser.java:117)
                            	at io.ticofab.androidgpxparser.parser.GPXParser.parse(GPXParser.java:83)
                            	at com.ideveloper.ui.activity.MapActivity.gpxTrackPoints(MapActivity.java:390)
                            	at com.ideveloper.ui.activity.MapActivity.access$1100(MapActivity.java:108)
                            	at com.ideveloper.ui.activity.MapActivity$6.onDownloadComplete(MapActivity.java:855)
                            	at com.downloader.request.DownloadRequest$2.run(DownloadRequest.java:260)
                            	at android.os.Handler.handleCallback(Handler.java:938)
                            	at android.os.Handler.dispatchMessage(Handler.java:99)
                            	at android.os.Looper.loopOnce(Looper.java:201)
                            	at android.os.Looper.loop(Looper.java:288)
                            	at android.app.ActivityThread.main(ActivityThread.java:7870)
                            	at java.lang.reflect.Method.invoke(Native Method)
                            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`
                            	
>Possible answers please drop.

Parser code
`GPXParser parser = new GPXParser(); // consider injection
        Gpx parsedGpx = null;
        try {
//            FileInputStream in = new FileInputStream(files);
            FileInputStream in = new FileInputStream(filePath);
            Log.d(TAG, "---->"+filePath);
            parsedGpx = parser.parse(in); // consider using a background thread
        } catch (IOException | XmlPullParserException e) {
            e.printStackTrace();
        }`

**Comment by aeiou-st** [comment]
This issue of GPX file that i'm parsing earlier and now it solved because of Date format issue
