### ISSUE TITLE
IllegalArgumentException while parsing GPX file

### ISSUE THREAD

**Issue by andreasflosdorf** [ticofab/android-gpx-parser#57]
One exception occurred while using your framework:

`Caused by: java.lang.IllegalArgumentException: Invalid format: "2024-12-04 10:42:31" is malformed at " 10:42:31"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:953)
	at io.ticofab.androidgpxparser.parser.GPXParser.readTime(GPXParser.java:500)
	at io.ticofab.androidgpxparser.parser.GPXParser.readMetadata(GPXParser.java:369)
	at io.ticofab.androidgpxparser.parser.GPXParser.readGpx(GPXParser.java:108)
	at io.ticofab.androidgpxparser.parser.GPXParser.parse(GPXParser.java:83)
	at de.flosdorf.routenavigation.service.GeoDataService.parseGpx(GeoDataService.java:1022)
	... 8 more
`

Working code is the following:
<img width="586" alt="image" src="https://github.com/user-attachments/assets/d53a9a2f-7e1b-43cb-9e82-e211f1f28da6">

Input data is a GPX file, please have a look at the attachments.
[Tourschnipsel.gpx.txt](https://github.com/user-attachments/files/18048992/Tourschnipsel.gpx.txt)

Can you please help me interpreting the error? What kan we do to avoid this behaviour?
Best regards,
Andreas

**Comment by ticofab** [comment]
Hi and thanks for reporting this issue. Unfortunately as the README states, I am no longer working on this project. 
https://github.com/ticofab/android-gpx-parser
